language: ruby
rvm:
  - 2.2.0

before_script:
  - git clone https://gist.github.com/6179925.git -b v2.0.beta3 kalibro_install
  - pushd kalibro_install
    # Remove bugged libzmq3 package, see https://github.com/travis-ci/travis-ci/issues/982 and https://github.com/travis-ci/travis-ci/issues/1715 for details
  - sudo apt-get remove libzmq3
  - sudo service postgresql stop
  - bash install.sh
  - popd
  - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml
  - export BUNDLE_GEMFILE=$PWD/Gemfile

script:
  - bundle exec rspec spec
  - bundle exec cucumber --tags ~@wip

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
