language: ruby
rvm:
  - 2.0.0-p247

before_script:
  - wget https://gist.github.com/rafamanzo/6179925/raw/77653bd6229e99d5251180a4488e2fa54d0cd4ac/db_bootstrap.sql
  - wget https://gist.github.com/rafamanzo/6179925/raw/172802a0db1ae88c3d5d3d3547833c45a5c9a7a2/install.sh
  - chmod +x install.sh
  - ./install.sh

script: 
  - bundle exec rspec spec
  - bundle exec cucumber

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
