language: ruby
rvm:
  - 2.3.0
  - 2.0.0-p598 # CentOS 7
  - 2.1.5 # Debian 8
addons:
  postgresql: "9.3"
sudo: false
cache:
  bundler: true
  directories:
    - $HOME/.cache/kalibro_install

before_install:
  - if ruby --version | cut -d ' ' -f 2 | grep -q 2.1.5p273 ; then gem update --system 2.4.8; fi
  - gem --version

before_script:
  - git clone https://github.com/mezuro/kalibro_install.git -b v4.0 kalibro_install
  - >
    KALIBRO_PROCESSOR_VERSION='v1.2.1' KALIBRO_CONFIGURATIONS_VERSION='v2.1.0' ANALIZO_VERSION=none
    CACHE_DIR=~/.cache/kalibro_install
    ./kalibro_install/install.sh
  - export CODECLIMATE_REPO_TOKEN=46cbb96b053b03ad66b0355bd96d0787f56fc5a4fc171b8d6eb30c421c5e6777

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
